### PR TITLE
Uses profanity library now.

### PR DESCRIPTION
**Pull request by NoahS2003**

### CODE REVIEW

**Comment by NoahS2003** [comment]
@Lionclaw49 pip3.5 install profanity before you merge

**Comment by NoahS2003** [comment]
Welp. No longer needed.

**Comment by NoahS2003** [comment]
The alternative library sucks.

**Comment by griffindugan** [comment]
it no worko tho

**Comment by NoahS2003** [comment]
It worketh now

**Comment by griffindugan** [comment]
Added manually.

**Pull request closed without merging**
